In [1]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/raw/sparkov/fraudTrain.csv")

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (1296675, 23)

Columns:
['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']

First 5 rows:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [2]:
# Remove the original CSV index column.
df = df.drop(columns=["Unnamed: 0"])

# Convert timestamp once and reuse it.
df["transaction_time"] = pd.to_datetime(df["trans_date_trans_time"])

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  str
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  str
 3   category               1296675 non-null  str
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  str
 6   last                   1296675 non-null  str
 7   gender                 1296675 non-null  str
 8   street                 1296675 non-null  str
 9   city                   1296675 non-null  str
 10  state                  1296675 non-null  str
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  str
 16  dob                    1296675 non-null  str
 17  trans_num              1296675 non-null  str
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
 22  transaction_time       1296675 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(5), int64(5), str(12)
memory usage: 426.6 MB

In [4]:
print("Missing values:")
display(df.isna().sum())

Missing values:

trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
transaction_time         0
dtype: int64

In [5]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [6]:
print("Number of columns:", len(df.columns))

for i, col in enumerate(df.columns):
    print(i, "->", col)

Number of columns: 23
0 -> trans_date_trans_time
1 -> cc_num
2 -> merchant
3 -> category
4 -> amt
5 -> first
6 -> last
7 -> gender
8 -> street
9 -> city
10 -> state
11 -> zip
12 -> lat
13 -> long
14 -> city_pop
15 -> job
16 -> dob
17 -> trans_num
18 -> unix_time
19 -> merch_lat
20 -> merch_long
21 -> is_fraud
22 -> transaction_time

In [7]:
fraud_counts = df["is_fraud"].value_counts()

print(fraud_counts)
print("\nPercentage:")
print(df["is_fraud"].value_counts(normalize=True) * 100)

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

Percentage:
is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64

In [8]:
print("Unique customers:", df["cc_num"].nunique())
print("Unique merchants:", df["merchant"].nunique())
print("Unique categories:", df["category"].nunique())
print("Unique cities:", df["city"].nunique())
print("Unique states:", df["state"].nunique())
print("Unique transaction IDs:", df["trans_num"].nunique())

Unique customers: 983
Unique merchants: 693
Unique categories: 14
Unique cities: 894
Unique states: 51
Unique transaction IDs: 1296675

In [9]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate transaction IDs:", df["trans_num"].duplicated().sum())

Duplicate rows: 0
Duplicate transaction IDs: 0

In [10]:
df["transaction_time"] = pd.to_datetime(df["trans_date_trans_time"])

print("Start:", df["transaction_time"].min())
print("End:", df["transaction_time"].max())
print("Number of days:",
      (df["transaction_time"].max() - df["transaction_time"].min()).days)

Start: 2019-01-01 00:00:18
End: 2020-06-21 12:13:37
Number of days: 537

In [11]:
print(df["amt"].describe())
print("Minimum:", df["amt"].min())
print("Maximum:", df["amt"].max())
print("Median:", df["amt"].median())

count    1.296675e+06
mean     7.035104e+01
std      1.603160e+02
min      1.000000e+00
25%      9.650000e+00
50%      4.752000e+01
75%      8.314000e+01
max      2.894890e+04
Name: amt, dtype: float64
Minimum: 1.0
Maximum: 28948.9
Median: 47.52

In [12]:
df.groupby("is_fraud")["amt"].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,1289169.0,67.667110,154.007971,1.00,9.6100,47.280,82.540,28948.90
1,7506.0,531.320092,390.560070,1.06,245.6625,396.505,900.875,1376.04

In [13]:
fraud_by_category = (
    df.groupby("category")["is_fraud"]
      .agg(
          transaction_count="count",
          fraud_count="sum",
          fraud_rate="mean"
      )
      .sort_values("fraud_rate", ascending=False)
)

fraud_by_category

                transaction_count  fraud_count  fraud_rate
category
shopping_net                97543         1713    0.017561
misc_net                    63287          915    0.014458
grocery_pos                123638         1743    0.014098
shopping_pos               116672          843    0.007225
gas_transport              131659          618    0.004694
misc_pos                    79655          250    0.003139
grocery_net                 45452          134    0.002948
travel                      40507          116    0.002864
entertainment               94014          233    0.002478
personal_care               90758          220    0.002424
kids_pets                  113035          239    0.002114
food_dining                 91461          151    0.001651
home                       123115          198    0.001608
health_fitness              85879          133    0.001549

In [14]:
customer_transaction_counts = (
    df.groupby("cc_num")["trans_num"]
      .count()
      .sort_values(ascending=False)
)

print("Customers:", customer_transaction_counts.shape[0])
print("Min transactions/customer:", customer_transaction_counts.min())
print("Max transactions/customer:", customer_transaction_counts.max())
print("Median transactions/customer:", customer_transaction_counts.median())

print("\nDistribution:")
display(customer_transaction_counts.describe())

Customers: 983
Min transactions/customer: 7
Max transactions/customer: 3123
Median transactions/customer: 1054.0

Distribution:

count     983.000000
mean     1319.099695
std       812.235900
min         7.000000
25%       525.000000
50%      1054.000000
75%      2025.000000
max      3123.000000
Name: trans_num, dtype: float64

In [15]:
customer_transaction_counts = (
    df.groupby("cc_num")["trans_num"]
      .count()
      .sort_values(ascending=False)
)

print("Customers:", customer_transaction_counts.shape[0])
print("Min transactions/customer:", customer_transaction_counts.min())
print("Max transactions/customer:", customer_transaction_counts.max())
print("Median transactions/customer:", customer_transaction_counts.median())

print("\nDistribution:")
display(customer_transaction_counts.describe())

Customers: 983
Min transactions/customer: 7
Max transactions/customer: 3123
Median transactions/customer: 1054.0

Distribution:

count     983.000000
mean     1319.099695
std       812.235900
min         7.000000
25%       525.000000
50%      1054.000000
75%      2025.000000
max      3123.000000
Name: trans_num, dtype: float64

In [16]:
fraud_by_customer = (
    df.groupby("cc_num")["is_fraud"]
      .agg(
          transaction_count="count",
          fraud_count="sum",
          fraud_rate="mean"
      )
      .sort_values("fraud_count", ascending=False)
)

fraud_by_customer.head(20)

                     transaction_count  fraud_count  fraud_rate
cc_num
3520550088202337                   989           19    0.019211
4593569795412                       19           19    1.000000
4260128500325                     1466           18    0.012278
4400011257587661852               2030           16    0.007882
2720433095629877                  3107           16    0.005150
6538891242532018                  3072           16    0.005208
3518669219150142                  2525           16    0.006337
3576021480694169                  2527           16    0.006332
4874006077381178                   516           16    0.031008
30074693890476                    2057           16    0.007778
3556613125071656                  2556           16    0.006260
6011366578560244                  2060           16    0.007767
3589289942931264                  2553           16    0.006267
4629451965224809                  1531           16    0.010451
3575540972310993                  1542           16    0.010376
2227671554547514                   545           16    0.029358
6506116513503136                  2102           15    0.007136
675945690716                      1570           15    0.009554
3521260686633367                    15           15    1.000000
371226440126102                   2534           15    0.005919